version: "3.3"
services:
  db-virtuoso:
    image: db-virtuoso-deploy
    volumes:
      - $DB_PATH/database:/database
      - ./db-virtuoso/initdb.d:/opt/virtuoso-opensource/initdb.d
      - ./db-virtuoso/script:/script
    environment:
      - DBA_PASSWORD=dba
    ports:
      - "1111:1111"
      - "8890:8890"
