# Environment variables:
#
# DB_VIRTUOSO_PATH  : directory for top-level of database storage
version: "3.3"
services:
  db-virtuoso:
    image: db-virtuoso-deploy
    volumes:
      - $DB_VIRTUOSO_PATH/database:/database
      - $DB_VIRTUOSO_PATH/data:/data
      - ./db-virtuoso/initdb.d:/opt/virtuoso-opensource/initdb.d
      - ./db-virtuoso/script:/script
      - ./graphs.yaml:/data/graphs.yaml
      - ./graph-meta:/data/graph-meta
    environment:
      - DBA_PASSWORD=dba
      # Add '/data' to `DirsAllowed` in `virtuoso.ini` file
      - 'VIRT_Parameters_DirsAllowed=., ../vad, /usr/share/proj, /data'
    ports:
      - "1111:1111"
      - "8890:8890"
