# Environment variables:
#
# DB_VIRTUOSO_PATH       : directory for top-level of database storage
# DB_VIRTUOSO_HTTP_PORT  : port for HTTP access
version: "3.3"
services:
  db-virtuoso:
    image: db-virtuoso-deploy
    volumes:
      - $DB_VIRTUOSO_PATH/database:/database
      - $DB_VIRTUOSO_PATH/data:/data
      - ./db-virtuoso/initdb.d:/opt/virtuoso-opensource/initdb.d
      - ./db-virtuoso/script:/script
      - ./graphs.yaml:/data/graphs.yaml
      - ./graph-meta:/data/graph-meta
    environment:
      - DBA_PASSWORD=dba
      # Add '/data' to `DirsAllowed` in `virtuoso.ini` file
      - 'VIRT_Parameters_DirsAllowed=., ../vad, /usr/share/proj, /data'
      # Set buffers. See
      # <https://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning>
      - "VIRT_Parameters_NumberOfBuffers=${DB_VIRTUOSO_Parameters_NumberOfBuffers:-10000}"
      - "VIRT_Parameters_MaxDirtyBuffers=${DB_VIRTUOSO_Parameters_MaxDirtyBuffers:-6000}"
    ports:
      - "1111:1111"
      - "${DB_VIRTUOSO_HTTP_PORT:-8890}:8890"
  reverse-proxy:
    image: nginx:1-alpine
    volumes:
      - ./db-virtuoso/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_REVERSE_PROXY_HTTP_PORT:-8900}:8080"
