# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use 
# dvc repro -f
# Individual stage can be executed using: 
# dvc repro <stage>

stages:
  bb_path:
    cmd: stages/00_bb_path.sh
    deps:
      - stages/00_bb_path.sh
    outs:
      - 'data-source/brick-manifest':
          push: false
  preprocess:
    cmd: stages/01_preprocess.sh
    deps:
      - stages/01_preprocess.sh
      - stages/process.ice.sql
    outs:
      - data-processed:
          push: false
  rml:
    cmd: stages/02_rml.sh
    deps:
      - stages/02_rml.sh
      - data-source/brick-manifest
      - data-processed
      - stages/bindingdb.rml.ttl
      - stages/chembl.rml.ttl
      - stages/ctdbase.rml.ttl
      - stages/ice.rml.ttl
      - stages/okg-ml.rml.ttl
      - stages/tox21.rml.ttl
      - stages/toxcast.rml.ttl
    outs:
      - raw:
          push: false
  build:
    cmd: stages/03_build.sh
    deps:
      - stages/03_build.sh
      - raw
    outs:
      - brick
