## DESCRIPTION:
##
## Count of distinct subjects in each graph (uses the graph prefix so that all
## files in a graph are aggregated).
SELECT ?g_prefix (SUM(?count) AS ?subject_count)
WHERE
{
  {
    SELECT ?g (COUNT(DISTINCT ?s) as ?count)
    WHERE {
      GRAPH ?g { ?s ?_p ?_o }
    }
    GROUP BY ?g
  }
  BIND( URI(STRBEFORE(STR(?g), '?file=')) AS ?g_prefix )
}
GROUP BY ?g_prefix
