## DESCRIPTION:
##
## List of graph names with the `file` suffix removed.
SELECT DISTINCT ?g_prefix
WHERE {
  GRAPH ?g { }
  BIND( URI(STRBEFORE(STR(?g), '?file=')) AS ?g_prefix )
}
ORDER BY ?g_prefix
