## DESCRIPTION:
##
## Look up assays from InvitroDB that are found in only ICE or only ToxCast.
##
## These are assays that have been renamed.

PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix CHEMINF: <http://purl.obolibrary.org/obo/CHEMINF_>
prefix CAS:     <http://identifiers.org/cas/>
PREFIX EDAM:    <http://edamontology.org/>
PREFIX dce:     <http://purl.org/dc/elements/1.1/>
PREFIX BAO:     <http://www.bioassayontology.org/bao#BAO_>

SELECT *
WHERE
{
	{
		SELECT
			?assay
			( GROUP_CONCAT(?g;separator=", ") AS ?graphs  )
			( COUNT(?g) AS ?g_count )
		WHERE {
			graph ?g {
				?assay  a            BAO:0000015 ;
					dce:source   "InvitroDB" .
			}
		}
		GROUP BY ?assay
	}
	FILTER( ?g_count < 2 )
}
ORDER BY ?assay